# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#2d1c0b"

# Main text color
theme[main_fg]="#fffcf0"

# Title color for boxes
theme[title]="#b5b5b5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#676159"

# Background color of selected item in processes box
theme[selected_bg]="#303030"

# Foreground color of selected item in processes box
theme[selected_fg]="#fffcf0"

# Color of inactive/disabled text
theme[inactive_fg]="#303030"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b5b5b5"

# Box outline and divider line color
theme[cpu_box]="#a2a2a2"
theme[mem_box]="#a2a2a2"
theme[net_box]="#a2a2a2"
theme[proc_box]="#a2a2a2"
theme[div_line]="#303030"

# Gradient for all meters and graphs
theme[temp_start]="#4b4844"
theme[temp_mid]="#b5b5b5"
theme[temp_end]="#857b6f"


theme[cpu_start]="#4b4844"
theme[cpu_mid]="#b5b5b5"
theme[cpu_end]="#857b6f"


theme[free_start]="#b5b5b5"
theme[free_mid]="#676159"
theme[free_end]="#676159"


theme[cached_start]="#676159"
theme[cached_mid]="#676159"
theme[cached_end]="#676159"


theme[available_start]="#4b4844"
theme[available_mid]="#4b4844"
theme[available_end]="#4b4844"


theme[used_start]="#857b6f"
theme[used_mid]="#857b6f"
theme[used_end]="#857b6f"


theme[download_start]="#676159"
theme[download_mid]="#4b4844"
theme[download_end]="#b5b5b5"


theme[upload_start]="#676159"
theme[upload_mid]="#4b4844"
theme[upload_end]="#b5b5b5"
